@echo off
echo Installing backend dependencies...
pip install -r requirements.txt
echo Starting AIVALA Security Backend on http://localhost:8000 ...
uvicorn main:app --host 0.0.0.0 --port 8000 --reload
pause
